export default {
  data() {
    return {
      navMenu: [
        {
          title: "Товары",
          icon: "el-icon-star-off",
          path: "product",
          line: false,
          disabled: false,
        },
        {
          title: "Каталог",
          icon: "el-icon-reading",
          path: "",
          line: false,
          disabled: false,
        },
        {
          title: "Брэнды",
          icon: "el-icon-price-tag",
          path: "",
          line: false,
          disabled: false,
        },
        {
          title: "Цвета",
          icon: "el-icon-brush",
          path: "",
          line: false,
          disabled: false,
        },
        {
          title: "Таблицы размеров",
          icon: "el-icon-crop",
          path: "",
          line: true,
          disabled: false,
        },
        {
          title: "Заказы",
          icon: "el-icon-shopping-cart-2",
          path: "",
          line: false,
          disabled: false,
        },
        {
          title: "Клиенты",
          icon: "el-icon-tickets",
          path: "",
          line: true,
          disabled: false,
        },
        {
          title: "Баннеры",
          icon: "el-icon-files",
          path: "",
          line: false,
          disabled: false,
        },
        {
          title: "Сторис",
          icon: "el-icon-copy-document",
          path: "",
          line: false,
          disabled: false,
        },
        {
          title: "Подборки",
          icon: "el-icon-shopping-bag-1",
          path: "",
          line: true,
          disabled: false,
        },
        {
          title: "Рубрики",
          icon: "el-icon-collection-tag",
          path: "",
          line: false,
          disabled: false,
        },
        {
          title: "Материалы",
          icon: "el-icon-coin",
          path: "",
          line: true,
          disabled: false,
        },
        {
          title: "Скидки",
          icon: "el-icon-coin",
          path: "",
          line: false,
          disabled: false,
        },
        {
          title: "Промокоды",
          icon: "el-icon-present",
          path: "",
          line: false,
          disabled: false,
        },
        {
          title: "Сертификаты",
          icon: "el-icon-bank-card",
          path: "catalog",
          line: true,
          disabled: false,
        },
        {
          title: "Главный экран",
          icon: "el-icon-house",
          path: "",
          line: false,
          disabled: false,
        },
        {
          title: "Инфостраницы",
          icon: "el-icon-warning-outline",
          path: "",
          line: true,
          disabled: false,
        },
        {
          title: "Пользователи",
          icon: "el-icon-set-up",
          path: "",
          line: false,
          disabled: false,
        },
        {
          title: "Настройки",
          icon: "el-icon-setting",
          path: "",
          line: false,
          disabled: false,
        },
      ]
    }
  }
}